// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Data;

namespace Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Repository.Models.Garden", b =>
                {
                    b.Property<int>("GardenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("GardenType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Organic")
                        .HasColumnType("bit");

                    b.Property<string>("PlotSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VolunteerOpportunities")
                        .HasColumnType("bit");

                    b.Property<double>("Zip")
                        .HasColumnType("float");

                    b.HasKey("GardenId");

                    b.ToTable("Garden");

                    b.HasData(
                        new
                        {
                            GardenId = 1,
                            City = "Milwaukee",
                            Cost = 0.0,
                            GardenType = "Urban Farm",
                            Latitude = 43.058630000000001,
                            Longitude = -87.938800000000001,
                            Name = "Alice's Garden Urban Farm",
                            Organic = false,
                            PlotSize = "Cooperative",
                            State = "Wisconsin",
                            StreetAddress = "2136 N. 21st St.",
                            VolunteerOpportunities = true,
                            Zip = 53205.0
                        },
                        new
                        {
                            GardenId = 2,
                            City = "West Bend",
                            Cost = 15.0,
                            GardenType = "Vegetable",
                            Latitude = 43.396120000000003,
                            Longitude = -88.180239999999998,
                            Name = "Community Church Garden",
                            Organic = false,
                            PlotSize = "10 X 20",
                            State = "Wisconsin",
                            StreetAddress = "2005 S. Main St.",
                            VolunteerOpportunities = false,
                            Zip = 53095.0
                        },
                        new
                        {
                            GardenId = 3,
                            City = "Milwaukee",
                            Cost = 45.0,
                            GardenType = "Vegetable",
                            Latitude = 43.067729999999997,
                            Longitude = -87.890789999999996,
                            Name = "Urban Ecology Center- Riverside Park",
                            Organic = true,
                            PlotSize = "10 X 15",
                            State = "Wisconsin",
                            StreetAddress = "1500 E Park Place",
                            VolunteerOpportunities = false,
                            Zip = 53211.0
                        },
                        new
                        {
                            GardenId = 4,
                            City = "Milwaukee",
                            Cost = 20.0,
                            GardenType = "Vegetable",
                            Latitude = 42.976730000000003,
                            Longitude = -87.986170000000001,
                            Name = "Our Common Home Community Garden",
                            Organic = false,
                            PlotSize = "4 X 10",
                            State = "Wisconsin",
                            StreetAddress = "3722 S. 58th St.",
                            VolunteerOpportunities = true,
                            Zip = 53220.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
